fezjo
trojsten/sortiment pull request #33
Opened 2023-03-14 15:23 UTC by fezjo

2023-03-16 21:50 UTC, gardenerik requested changes
Keď vytvorím nový produkt, Späť ma nevráti nikam. 

~Nezobrazujú sa mi žiadne produkty :(~

2023-04-04 11:26 UTC, fezjo commented
1. resolved
2. lie

2023-04-09 22:01 UTC, gardenerik requested changes
Produkty, ktoré nie sú na sklade sa nezobrazujú.

2023-04-12 15:51 UTC, gardenerik approved these changes

2023-04-12 15:54 UTC, merged